#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc32
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-tWC -- Console application
#
CFLAGS=-N -v -w -tWC
all: tmp-name.exe

tmp-name.exe: tmp-name.cpp
	$(CC) $(CFLAGS) -etmp-name tmp-name.cpp

clean:
	erase tmp-name.exe
