#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc32
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-tWC -- Console application
#
CFLAGS=-N -v -w -tWC
all: max.exe

max.exe: max.cpp
	@echo "This compile generates a warning"
	$(CC) $(CFLAGS) -emax max.cpp

clean:
	erase max.exe
