#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc32
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-tWC -- Console application
#
CFLAGS=-N -v -w -tWC
all: tterm.exe

tterm.exe: tterm.cpp
	$(CC) $(CFLAGS) -etterm tterm.cpp

clean:
	erase tterm.exe
