#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	GZ -- Enable stack checking
#	RTCsuc -- Enable all runtime checks
#	Zi -- Enable debugging
#	Wall -- Turn on warnings (Omitted)
#	EHsc -- Turn exceptions on

#
CFLAGS=/GZ /RTCsuc /Zi /EHsc 
all: exp.exe

exp.exe: exp.cpp
	@echo "Expect a null effect warning"
	$(CC) $(CFLAGS)  exp.cpp

clean:
	erase exp.exe
