#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc32
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-tWC -- Console application
#
CFLAGS=-N -v -w -tWC
all: double.exe

double.exe: double.cpp
	$(CC) $(CFLAGS) -edouble double.cpp

clean:
	erase double.exe
