#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc32
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-tWC -- Console application
#
CFLAGS=-N -v -w -tWC
all: twoc.exe

twoc.exe: twoc.cpp
	$(CC) $(CFLAGS) -etwoc twoc.cpp

clean:
	erase twoc.exe
