#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc32
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-tWC -- Console application
#
CFLAGS=-N -v -w -tWC
all: tri.exe

tri.exe: tri.cpp
	$(CC) $(CFLAGS) -etri tri.cpp

clean:
	erase tri.exe
