#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc32
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-tWC -- Console application
#
CFLAGS=-N -v -w -tWC
all: sam.exe

sam.exe: sam.cpp
	$(CC) $(CFLAGS) -esam sam.cpp

clean:
	erase sam.exe
