#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc32
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-tWC -- Console application
#
CFLAGS=-N -v -w -tWC
all: array-p.exe

array-p.exe: array-p.cpp
	$(CC) $(CFLAGS) -earray-p array-p.cpp

clean:
	erase array-p.exe
