#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc32
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-tWC -- Console application
#
CFLAGS=-N -v -w -tWC
all: print.exe

print.exe: print.cpp
	$(CC) $(CFLAGS) -eprint print.cpp

clean:
	erase print.exe
