#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc32
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-tWC -- Console application
#
CFLAGS=-N -v -w -tWC
two: two.cpp
	$(CC) $(CFLAGS) -etwo two.cpp

clean:
	erase two
