#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc32
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-tWC -- Console application
#
CFLAGS=-N -v -w -tWC
all: wbin.exe

wbin.exe: wbin.cpp
	$(CC) $(CFLAGS) -ewbin wbin.cpp

clean:
	erase wbin.exe
