#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	GZ -- Enable stack checking
#	RTCsuc -- Enable all runtime checks
#	Zi -- Enable debugging
#	Wall -- Turn on warnings (Omitted)
#	EHsc -- Turn exceptions on

#
CFLAGS=/GZ /RTCsuc /Zi /EHsc 
all: name2.exe

name2.exe: name2.cpp
	$(CC) $(CFLAGS)  name2.cpp

clean:
	erase name2.exe
