#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc32
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-tWC -- Console application
#
CFLAGS=-N -v -w -tWC
all: name2.exe

name2.exe: name2.cpp
	$(CC) $(CFLAGS) -ename2 name2.cpp

clean:
	erase name2.exe
