#
# Makefile for many UNIX compilers using the
# "standard" command name CC
#
CC=CC
CFLAGS=-g
all: good bad

good: good.cpp
	$(CC) $(CFLAGS) -o good good.cpp

bad: bad.cpp
	$(CC) $(CFLAGS) -o bad bad.cpp

clean:
	rm good bad
