#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc32
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-tWC -- Console application
#
CFLAGS=-N -v -w -tWC
all: good.exe bad.exe

good.exe: good.cpp
	$(CC) $(CFLAGS) -egood good.cpp

bad.exe: bad.cpp
	$(CC) $(CFLAGS) -ebad bad.cpp

clean:
	erase good.exe bad.exe
