#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	GZ -- Enable stack checking
#	RTCsuc -- Enable all runtime checks
#	Zi -- Enable debugging
#	Wall -- Turn on warnings (Omitted)
#	EHsc -- Turn exceptions on

#
CFLAGS=/GZ /RTCsuc /Zi /EHsc 
all: good.exe bad.exe

good.exe: good.cpp
	$(CC) $(CFLAGS)  good.cpp

bad.exe: bad.cpp
	$(CC) $(CFLAGS)  bad.cpp

clean:
	erase good.exe bad.exe
