#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc32
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-tWC -- Console application
#
CFLAGS=-N -v -w -tWC
stack_s.exe: stack_s.cpp
	$(CC) $(CFLAGS) -estack_s stack_s.cpp

clean:
	erase stack_s.exe
