#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	GZ -- Enable stack checking
#	RTCsuc -- Enable all runtime checks
#	Zi -- Enable debugging
#	Wall -- Turn on warnings (Omitted)
#	EHsc -- Turn exceptions on

#
CFLAGS=/GZ /RTCsuc /Zi /EHsc 
all: ptr2.exe ptr2a.exe

ptr2a.exe: ptr2a.cpp
	$(CC) $(CFLAGS)  ptr2a.cpp

ptr2.exe: ptr2.cpp
	$(CC) $(CFLAGS)  ptr2.cpp

clean:
	erase ptr2.exe ptr2a.exe
