#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc32
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-tWC -- Console application
#
CFLAGS=-N -v -w -tWC
all: total.exe

total.exe: total.cpp
	$(CC) $(CFLAGS) -etotal total.cpp

clean:
	erase total.exe
