#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc32
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-tWC -- Console application
#
CFLAGS=-N -v -w -tWC
all: float.exe

float.exe: float.cpp
	$(CC) $(CFLAGS) -efloat float.cpp

clean:
	erase float.exe
