#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc32
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-tWC -- Console application
#
CFLAGS=-N -v -w -tWC
all: cent.exe

cent.exe: cent.cpp
	$(CC) $(CFLAGS) -ecent cent.cpp

clean:
	erase cent.exe

