#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	GZ -- Enable stack checking
#	RTCsuc -- Enable all runtime checks
#	Zi -- Enable debugging
#	Wall -- Turn on warnings (Omitted)
#	EHsc -- Turn exceptions on

#
CFLAGS=/GZ /RTCsuc /Zi /EHsc 
all: copy2.exe

copy2.exe: copy2.cpp
	$(CC) $(CFLAGS) -D__WIN32__ copy2.cpp

clean:
	erase copy2.exe
