#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc32
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-tWC -- Console application
#
CFLAGS=-N -v -w -tWC
all: copy2.exe

copy2.exe: copy2.cpp
	$(CC) $(CFLAGS) -D__WIN32__ -ecopy2 copy2.cpp

clean:
	erase copy2.exe
