#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc32
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-tWC -- Console application
#
CFLAGS=-N -v -w -tWC
class.obj: class.cpp
	@echo "This does not generate a full program"
	$(CC) $(CFLAGS) -c class.cpp

clean:
	erase class.obj
