#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc32
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-tWC -- Console application
#
CFLAGS=-N -v -w -tWC
all: float2.exe

float2.exe: float2.cpp
	$(CC) $(CFLAGS) -efloat2 float2.cpp

clean:
	erase float2.exe
