#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	GZ -- Enable stack checking
#	RTCsuc -- Enable all runtime checks
#	Zi -- Enable debugging
#	Wall -- Turn on warnings (Omitted)
#	EHsc -- Turn exceptions on

#
CFLAGS=/GZ /RTCsuc /Zi /EHsc 
all: float2.exe

float2.exe: float2.cpp
	$(CC) $(CFLAGS)  float2.cpp

clean:
	erase float2.exe
