#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc32
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-tWC -- Console application
#
CFLAGS=-N -v -w -tWC
all: total6.exe total6w.exe

total6.exe: total6.cpp
	$(CC) $(CFLAGS) -etotal6 total6.cpp

total6w.exe: total6w.cpp
	$(CC) $(CFLAGS) -etotal6w total6w.cpp

clean:
	erase total6.exe total6w.exe
