#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc32
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-tWC -- Console application
#
CFLAGS=-N -v -w -tWC
all: print3.exe

print3.exe: print3.cpp
	$(CC) $(CFLAGS) -eprint3 print3.cpp

clean:
	erase print3.exe
