#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc32
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-tWC -- Console application
#
CFLAGS=-N -v -w -tWC
equal.exe: equal.cpp
	$(CC) $(CFLAGS) -eequal equal.cpp

clean:
	erase equal.exe
