#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc32
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-tWC -- Console application
#
CFLAGS=-N -v -w -tWC
all: seven.exe count.exe

count.exe: count.cpp
	$(CC) $(CFLAGS) -ecount count.cpp

seven.exe: seven.cpp
	$(CC) $(CFLAGS) -eseven seven.cpp

clean:
	erase seven.exe count.exe
