#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	GZ -- Enable stack checking
#	RTCsuc -- Enable all runtime checks
#	Zi -- Enable debugging
#	Wall -- Turn on warnings (Omitted)
#	EHsc -- Turn exceptions on

#
CFLAGS=/GZ /RTCsuc /Zi /EHsc 
all: rec.exe

rec.exe: rec.cpp
	@echo "This compile will generate an error"
	-$(CC) $(CFLAGS)  rec.cpp

clean:
	erase rec.exe
