#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc32
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-tWC -- Console application
#
CFLAGS=-N -v -w -tWC
all: float1.exe

float1.exe: float1.cpp
	@echo "This program will generate a warning when compiled"
	$(CC) $(CFLAGS) -efloat1 float1.cpp

clean:
	erase float1.exe
