#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	GZ -- Enable stack checking
#	RTCsuc -- Enable all runtime checks
#	Zi -- Enable debugging
#	Wall -- Turn on warnings (Omitted)
#	EHsc -- Turn exceptions on

#
CFLAGS=/GZ /RTCsuc /Zi /EHsc 
all: def.exe

def.exe: def.cpp
	$(CC) $(CFLAGS)  def.cpp

clean:
	erase def.exe
