#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	GZ -- Enable stack checking
#	RTCsuc -- Enable all runtime checks
#	Zi -- Enable debugging
#	Wall -- Turn on warnings (Omitted)
#	EHsc -- Turn exceptions on

#
CFLAGS=/GZ /RTCsuc /Zi /EHsc 
all: balance.exe

balance.exe: balance.cpp
	@echo "The following compile may generate a warning"
	$(CC) $(CFLAGS)  balance.cpp

clean:
	erase balance.exe
