#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc32
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-tWC -- Console application
#
CFLAGS=-N -v -w -tWC
all: calc3.exe

calc3.exe: calc3.cpp
	$(CC) $(CFLAGS) -ecalc3 calc3.cpp

clean:
	erase calc3.exe
