#
# Makefile for Microsoft Visual C++
#
C_COMPILE=cl
#
# Flags 
#	GZ -- Enable stack checking
#	RTCsuc -- Enable all runtime checks
#	Zi -- Enable debugging
#	Wall -- Turn on warnings (Omitted)
#	EHsc -- Turn exceptions on

#
CFLAGS=/GZ /RTCsuc /Zi /EHsc 
fun-file.exe: fun-file.cpp
	$(C_COMPILE) $(CFLAGS)  fun-file.cpp

clean:
	erase fun-file.exe
