#
# Makefile for many UNIX compilers using the
# "standard" command name CC
#
CC=CC
CFLAGS=-g
all: max stack_c1

max: max.cpp
	$(CC) $(CFLAGS) -o max max.cpp

stack_c1: stack_c1.cpp
	$(CC) $(CFLAGS) -o stack_c1 stack_c1.cpp

words: words.cpp
	$(CC) -v $(CFLAGS) -o words words.cpp

words.cpp: words.cc
	$(CC) -E $(CFLAGS) words.cpp>words.cc

clean:
	rm max stack_c1
