#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc32
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-tWC -- Console application
#
CFLAGS=-N -v -w -tWC
all: tmp2.exe

tmp2.exe: tmp2.cpp
	$(CC) $(CFLAGS) -etmp2 tmp2.cpp

clean:
	erase tmp2.exe
