#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	GZ -- Enable stack checking
#	RTCsuc -- Enable all runtime checks
#	Zi -- Enable debugging
#	Wall -- Turn on warnings (Omitted)
#	EHsc -- Turn exceptions on

#
CFLAGS=/GZ /RTCsuc /Zi /EHsc 
all: first.exe first.out

first.exe: first.cpp
	$(CC) $(CFLAGS)  first.cpp

first.out: first.cpp
	cl $(CFLAGS) -E first.cpp >first.out

clean:
	erase first.out first.exe
