#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc32
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-tWC -- Console application
#
CFLAGS=-N -v -w -tWC
all: first.exe first.out

first.exe: first.cpp
	$(CC) $(CFLAGS) -efirst first.cpp

first.out: first.cpp
	cpp first.cpp >first.out

clean:
	erase first.out first.exe
