#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc32
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-tWC -- Console application
#
CFLAGS=-N -v -w -tWC
all: tmp3.exe

tmp3.exe: tmp3.cpp
	@echo "This causes a compiler error"
	$(CC) $(CFLAGS) -etmp3 tmp3.cpp

clean:
	erase tmp3.exe
