#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc32
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-tWC -- Console application
#
CFLAGS=-N -v -w -tWC
complex.obj: complex.cpp complex.h
	$(CC) $(CFLAGS) -c complex.cpp

clean:
	erase complex.obj
